[package]
name = "wgmeeting_github_ircbot"
version = "0.3.8"
authors = ["L. David Baron <dbaron@dbaron.org>"]
build = "build.rs"

[dependencies]
futures = { version = "0.3", features = ["compat"] }
futures01 = { package = "futures", version = "0.1" }
log = "0.4"
env_logger = "0.7"
lazy_static = "1.4"
regex = "1.3"
tokio-core = "0.1" # should upgrade from tokio-core to tokio once hubcaps supports it
tokio-io = "0.1"
tokio-codec = "0.1"
hubcaps = "0.6.1"
serde = "1.0"
serde_derive = "1.0"
diff = "0.1"
toml = "0.5"

[dependencies.irc]
version = "0.13"
default-features = false
features = ["ctcp"]
