[package]
name = "wgmeeting_github_ircbot"
version = "0.4.0"
authors = ["L. David Baron <dbaron@dbaron.org>"]
build = "build.rs"
edition = "2018"

[dependencies]
failure = "0.1"
futures = { version = "0.3" }
log = "0.4"
env_logger = "0.7"
irc = { version = "0.14", default-features = false, features = ["ctcp", "tls-native", "serde"] }
lazy_static = "1.4"
regex = "1.3"
tokio = { version = "0.2", features = ["rt-core", "time", "io-util", "tcp"] }
hubcaps = "0.6.1"
serde = "1.0"
serde_derive = "1.0"
diff = "0.1"
toml = "0.5"
pin-utils = "0.1"

