# documentation at "rustfmt --help=config"
# documentation at https://github.com/rust-lang-nursery/rustfmt/blob/master/src/config.rs
#error_on_line_overflow = false # only available on nightly channel
edition = "2018"
wrap_comments = true
#format_strings = true # only available on nightly channel
normalize_comments = true

#spaces_around_ranges = true # only available on nightly channel
use_try_shorthand = true
